Update release pipeline and build multiarch images

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -5,33 +5,64 @@ on:
     - master
     tags:
     - v*
+  pull_request: {}
 
 jobs:
   build:
     runs-on: ubuntu-latest
     env:
-      IMAGE: docker.io/${{ github.repository }}
+      IMAGE: "${{ github.event_name == 'pull_request' && 'ghcr.io' || 'docker.io' }}/${{ github.repository }}"
     steps:
     - uses: actions/checkout@v6
       with:
-        fetch-depth: "0"
+        fetch-depth: 0 # NOTE(aa): Required in order to have tag information available
+    - name: Get version information
+      id: get-version-info
+      run: |
+        GITVERSION="$(git describe --tags --always --match=v* --dirty=+dirty || (echo "command failed $?"; exit 1))"
+        PYVERSION="$(git describe --tags --always --match=v* | cut -d- -f1,2 || (echo "command failed $?"; exit 1))"
+        echo "git version: $GITVERSION, pyversion: $PYVERSION"
+        echo "gitversion=${GITVERSION}" >> ${GITHUB_OUTPUT}
+        echo "pyversion=${PYVERSION}" >> ${GITHUB_OUTPUT}
+    - name: Set up QEMU
+      uses: docker/setup-qemu-action@v3
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v3
     - name: Set image version latest
       if: github.ref == 'refs/heads/master'
       run: echo "VERSION=latest" >> ${GITHUB_ENV}
+    - name: Set image version for PRs to branch name
+      if: github.event_name == 'pull_request'
+      run: echo "VERSION=${GITHUB_HEAD_REF//\//-}" >> ${GITHUB_ENV}
     - name: Set image version from tag
       if: startsWith(github.ref, 'refs/tags/v')
       run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> ${GITHUB_ENV}
-    - name: Build Image
-      run: make docker
-      env:
-        IMAGE_NAME: "${IMAGE}:${VERSION}"
-    - name: Push Image
-      env:
-        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-      run: |
-        docker login docker.io --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
-        docker push "${IMAGE}:${VERSION}"
+    - name: Login to docker.io
+      if: github.event_name != 'pull_request'
+      uses: docker/login-action@v3
+      with:
+        registry: docker.io
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
+    - name: Login to ghcr.io
+      if: github.event_name == 'pull_request'
+      uses: docker/login-action@v3
+      with:
+        registry: ghcr.io
+        username: ${{ github.repository_owner }}
+        password: ${{ secrets.GITHUB_TOKEN }}
+    - name: Build and push
+      id: docker_build
+      uses: docker/build-push-action@v6
+      with:
+        platforms: linux/amd64,linux/arm64
+        push: true
+        tags: "${{ env.IMAGE }}:${{ env.VERSION }}"
+        cache-from: type=gha
+        cache-to: type=gha,mode=max
+        build-args: |
+          GITVERSION=${{ steps.get-version-info.outputs.gitversion }}
+          PYVERSION=${{ steps.get-version-info.outputs.pyversion }}
     - name: Build changelog from PRs with labels
       if: startsWith(github.ref, 'refs/tags/v')
       id: build_changelog
@@ -74,3 +105,14 @@ jobs:
         # Ensure target branch for release is "master"
         commit: master
         token: ${{ secrets.GITHUB_TOKEN }}
+    - name: Delete untagged container images
+      # We always delete all untagged container images after building an
+      # image. This way, there should never be stale untagged images laying
+      # around in the registry. In combination with the workflow that
+      # deletes PR tags after the PR is closed we should be able to keep the
+      # container image registry size in check.
+      uses: dataaxiom/ghcr-cleanup-action@v1
+      with:
+        token: ${{ secrets.GITHUB_TOKEN }}
+        package: ${{ github.event.repository.name }}
+        validate: true
